// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HomePage: typeof import('./src/views/home/HomePage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    XtxFooter: typeof import('./src/components/XtxFooter.vue')['default']
    XtxHeader: typeof import('./src/components/XtxHeader.vue')['default']
    XtxLayout: typeof import('./src/components/XtxLayout.vue')['default']
    XtxTopNav: typeof import('./src/components/XtxTopNav.vue')['default']
  }
}

export {}
